### ISSUE TITLE
Add edit history and rollback

### ISSUE THREAD

**Issue by quartata** [ArtOfCode-/qpixel#19]

**Comment by ArtOfCode-** [comment]
Shouldn't be too difficult, just add a `PostHistory` model and respective associations, then create a new `PostHistory` record when a post is edited.

Will likely need a polymorphic association so that it can belong to either a question or an answer.

**Comment by ArtOfCode-** [comment]
Mostly implemented now, just needs to be integrated into the UI.

**Comment by du76gvtrHG** [comment]
@quartata @ArtOfCode- You kicked me many times from all over StackExchange since 2011 especially from the JS room but I'm not going away before ironing out my skills or being given another opportunity to show I'm not the one who started the problem.

**Comment by du76gvtrHG** [comment]
@quartata @ArtOfCode- You kicked me many times from all over StackExchange since 2011 especially from the JS room but I'm not going away before ironing out my skills or being given another opportunity to show I'm not the one who started the problem.

**Comment by du76gvtrHG** [comment]
@quartata @ArtOfCode- You kicked me many times from all over StackExchange since 2011 especially from the JS room but I'm not going away before ironing out my skills or being given another opportunity to show I'm not the one who started the problem.

**Comment by du76gvtrHG** [comment]
@quartata @ArtOfCode- You kicked me many times from all over StackExchange since 2011 especially from the JS room but I'm not going away before ironing out my skills or being given another opportunity to show I'm not the one who started the problem.

**Comment by du76gvtrHG** [comment]
@quartata @ArtOfCode- You kicked me many times from all over StackExchange since 2011 especially from the JS room but I'm not going away before ironing out my skills or being given another opportunity to show I'm not the one who started the problem.

**Comment by du76gvtrHG** [comment]
@quartata @ArtOfCode- You kicked me many times from all over StackExchange since 2011 especially from the JS room but I'm not going away before ironing out my skills or being given another opportunity to show I'm not the one who started the problem.

**Comment by du76gvtrHG** [comment]
@quartata @ArtOfCode- You kicked me many times from all over StackExchange since 2011 especially from the JS room but I'm not going away before ironing out my skills or being given another opportunity to show I'm not the one who started the problem.

**Comment by wfrg342fd** [comment]
@quartata @ArtOfCode- You kicked me many times from all over StackExchange since 2011 especially from the JS room but I'm not going away before ironing out my skills or being given another opportunity to show I'm not the one who started the problem.

**Comment by wfrg342fd** [comment]
@quartata @ArtOfCode- You kicked me many times from all over StackExchange since 2011 especially from the JS room but I'm not going away before ironing out my skills or being given another opportunity to show I'm not the one who started the problem.

**Comment by wfrg342fd** [comment]
@quartata @ArtOfCode- You kicked me many times from all over StackExchange since 2011 especially from the JS room but I'm not going away before ironing out my skills or being given another opportunity to show I'm not the one who started the problem.

**Comment by wfrg342fd** [comment]
@quartata @ArtOfCode- You kicked me many times from all over StackExchange since 2011 especially from the JS room but I'm not going away before ironing out my skills or being given another opportunity to show I'm not the one who started the problem.

**Comment by wfrg342fd** [comment]
@quartata @ArtOfCode- You kicked me many times from all over StackExchange since 2011 especially from the JS room but I'm not going away before ironing out my skills or being given another opportunity to show I'm not the one who started the problem.

**Comment by df87878fdeh** [comment]
@quartata @ArtOfCode-  that's no random garbage. I can't remember exactly if it was 2011, 2012 or slightly later but that was the period I'm mentioning. Maybe you weren't even on stackoverflow to begin with, so you don't know what was going on at that time. Ask JS room owners and they'll know. Heck even the moderators do.

**Comment by df87878fdeh** [comment]
@quartata @ArtOfCode- There was that guy with a lemon name and smiley avatar who was one to start the problem and the one who just talked with shog9 on the tavern the other day because he also was having problems on that JS room...
