### ISSUE TITLE
Error: undefined method `id' for nil:NilClass

### ISSUE THREAD

**Issue by somebody1234** [ArtOfCode-/qpixel#21]
Go [here](http://stage.artofcode.co.uk/users/5) to reproduce.

Details:

Code: 

    <p><a href="/questions/<%= answer.question.id %>"><%= answer.question.title %></a></p>

Trace of template inclusion: app/views/users/show.html.erb

Request Parameters: `{"id"=>"5"}`

**Comment by schas002** [comment]
ninja'd

**Comment by ArtOfCode-** [comment]
Gonna blame deleted posts and default scopes for this one.

**Comment by ArtOfCode-** [comment]
Fixed by 5521c9b8598a0dc0ed5f7bfd4af0b9376f625452
