### ISSUE TITLE
deleting answers on the demo platform causes error

### ISSUE THREAD

**Issue by grindhold** [ArtOfCode-/qpixel#24]
![error](https://i.imgur.com/IiqSLkf.png)

When i am on a question as registered user, I have an edit and a delete button. It was a fresh user, so my reputation was most likely not high enough to delete or edit the question.
To reproduce: Try to delete a question that is not yours with a fresh user.

Which leads to another question: Why are the edit/delete buttons being drawn when the user can't use them yet anyway. I think they should only be drawn if the user is admin, owner or has enough reputation.

**Comment by ArtOfCode-** [comment]
Yeah, I discovered this bug about two minutes before you posted it while running some tests 👍 

I haven't quite figured out what causes it, but I've done a few things and I *think* it's fixed.

As for unnecessary rendering - yeah, it's a tradeoff between unnecessary rendering or a few more DB queries and a slower response.
