### ISSUE TITLE
Add RSS feed support

### ISSUE THREAD

**Issue by schas002** [ArtOfCode-/qpixel#25]

**Comment by schas002** [comment]
This is an idea I just had. You can easily track new questions within your favorite RSS reader. Or SE chat, if you prefer. :d

**Comment by ArtOfCode-** [comment]
Shouldn't be too difficult. It's Rails, it's built for this kind of stuff.

**Comment by ArtOfCode-** [comment]
@schas002 [status-completed]; http://stage.artofcode.co.uk/questions/feed.rss
