### ISSUE TITLE
Demo server down

### ISSUE THREAD

**Issue by creativetags** [ArtOfCode-/qpixel#26]
http://stage.artofcode.co.uk appears to be down/gone. Anywhere I can see qpixel in action?

**Comment by ArtOfCode-** [comment]
Demo server is currently being used as a dev server for another project, but there's nothing happening on that today. I'll bring qpixel back up on it.

**Comment by ArtOfCode-** [comment]
Back up. I'll leave it there until I need the server for something else, which should be at least 24 hours.
