### ISSUE TITLE
Problems with Installation / Webpage Offline

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [ArtOfCode-/qpixel#27]
Hello,

You should have a couple of screen shots of the application, which is AMAZING!
So that people will contribute more..

I will contribute, if you have any tips I would really appreciate.

Thanks a lot
Fabrizio

**Comment by schas002** [comment]
> Thanks a lot for sharing your project on Github.

@fabriziobertoglio1987 You are welcome :smile:

> I wanted to see how was it, I tried to install but I had some errors.

Which errors?

> Unlucky your webpage is not working and I am not able to check how is your project...

Right now @ArtOfCode- has his stage subdomain dismantled and their site is now a portfolio. :/

**Comment by fabriziobertoglio1987** [comment]
Sorry, I updated my question! I just installed the app it is really good. It works. I fixed the errors, just the letsencrypt file was missing. No issue. 

So I want to continue his work..

**Comment by ArtOfCode-** [comment]
I can probably put an instance of QPixel back online for a while, if that's helpful.

@fabriziobertoglio1987 - you'll need to fork this repo as a first step: click the fork button in the top right. Then, you'll need these commands:

 - Clone your fork: `git clone https://github.com/fabriziobertoglio1987/qpixel`
 - `cd qpixel`
 - Do whatever work you want to do
 - `git add .`
 - `git commit -m "<insert a useful commit message>"`
 - `git push origin master`
 - Visit your repository on GitHub, and there'll be a button to start a pull request back to this repository somewhere.

**Comment by schas002** [comment]
> I can probably put an instance of QPixel back online for a while, if that's helpful.

Make a QPixel sandbox and QPixel Meta. :3

**Comment by fabriziobertoglio1987** [comment]
Ok thanks a lot. I will follow your forking instructions. That is very useful for me. I will probably do the QPixel Sandbox and also before launching I will try to create a meta, as It will be very useful for the community. 
Once I will be confident with Rspec, I will start building and I hope that you will be able to see my work online in 2/3 weeks. 

Thanks 
Fabrizio

**Comment by schas002** [comment]
Looking forward to your work, Fabrizio :sunglasses:

**Comment by fabriziobertoglio1987** [comment]
Thanks a lot :)

**Comment by ArtOfCode-** [comment]
@schas002 That'd just be two separate instances with slightly different styles, which just ain't worth it for the spare capacity I'd need on my server

**Comment by schas002** [comment]
@ArtOfCode- So do one instance with [meta] tag?

**Comment by ArtOfCode-** [comment]
@schas002 That sounds a lot like the original SO, using the site itself for meta. If I do put this up again, it's only going to be temporary. There's no point getting too invested in the details.

**Comment by fabriziobertoglio1987** [comment]
I want to build something like team Treehouse, but just for Q&A, as I may have in the future the time to do some tutoring. It would be like having a shared private tutor. So I will build functionalities connected to monthly subscriptions or integrate them from other Opensource projects.

**Comment by fabriziobertoglio1987** [comment]
Hello @ArtOfCode-  I just forked your project and I am starting work on this right now. 
Thanks for the very clear instructions
Fabrizio
