### ISSUE TITLE
Test Suite

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [ArtOfCode-/qpixel#28]
Hi, 
I wanted to run your test suite on my local machine. I though you use Minitest, but I get this error when I run the test suite 

```
ruby admin_controller_test.rb
/home/fabrizio/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- test_helper (LoadError)
	from /home/fabrizio/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from admin_controller_test.rb:1:in `<main>'
```
I did not try to fix this, looks like it is some problem with the gemfile... 

Any help very appreciated 
Thanks a lot 
Fabrizio

**Comment by ArtOfCode-** [comment]
Run `rake test`, not `ruby`

**Comment by fabriziobertoglio1987** [comment]
thanks !

I am changing db to `postgresql`, I am installing stripe, deploying to heroku then I will keep adding some new functionalities..

Would be great keeping it all togheter with the original project
I write test with Rspec

thanks a lot
Fabrizio
