### ISSUE TITLE
Why can't I post this comment?

### ISSUE THREAD

**Issue by cellio** [ArtOfCode-/qpixel#43]
I am trying to add the following comment to Boondoggle's answer on [this question](https://qpixel.artofcode.co.uk/questions/25663):

> This is basically what we did.  We wrote some JavaScript; when you select text you get a "comment" icon, and if you click on it you get a textbox.  Areas with comments are highlighted and you get the comment on mouse-over, and we also add a page with all the comments (and links) into the build output.  On the back end it's all stored in a SQLLite database.  We still need to add responses; right now we're hacking that by editing the comment to add responses where needed.

I click "post", but nothing happens.  I've tried shortening it (cutting from "on the back end"), but that didn't help.  I then tried posting a very short comment ("test comment") on user29102's answer on the same question, which also doesn't work.  Short comments on some other questions did work.

What's going on with this question?

**Comment by ArtOfCode-** [comment]
The `comments.content` field in the database is a `VARCHAR(255)`... I thought it was a `TEXT` field, but apparently not. Just needs a simple DB migration to fix.

**Comment by ArtOfCode-** [comment]
3e192a4
