### ISSUE TITLE
Voting seems to bump posts

### ISSUE THREAD

**Issue by cellio** [ArtOfCode-/qpixel#44]
It appears that merely voting on a question or any of its answers bumps the post on the main page.  For example, a couple hours I voted on an answer to [this question](https://qpixel.artofcode.co.uk/questions/25663), and that bumped the question to the top.  I noticed this a few days ago and thought I reported it but I can't find it now, so maybe I only imagined doing that.

I don't think voting should bump.  In addition to the mystery of a bump with no edits, it also runs the risk of exposing who did the voting.

**Comment by ArtOfCode-** [comment]
You did report this before - it's in #39 - and I thought I'd fixed it, but if it's still happening then clearly not. I'll take another look.

**Comment by ArtOfCode-** [comment]
[status-norepro] - I just voted on both question and answer on [this post](https://qpixel.artofcode.co.uk/questions/25663), and it's still saying last active 15 hours ago.

**Comment by cellio** [comment]
Huh, weird.  I'm not seeing it today either, but I did last night (on a different machine in a different browser, not that that should matter).  Sorry for the noise.

**Comment by ArtOfCode-** [comment]
I'll do some more testing when I'm next back at a proper dev env, but I _think_ this is fixed.

**Comment by ArtOfCode-** [comment]
Haven't been able to repro this either on live or in dev, so I'm tentatively closing for now. If this comes back, I can reopen.
