### ISSUE TITLE
Could "new answer" notifications link to the answer rather than the question?

### ISSUE THREAD

**Issue by cellio** [ArtOfCode-/qpixel#52]
Now that we have permalinks for answers (thanks!), could the link in the notification for a new answer link to the answer directly?  I just got such a notification on a question with many answers, and since the notification neither linked to the answer nor told me who it was by, I had to page through looking for the new one.  (I'd rather the answer to this request not be "sort answers by age", as that's more heavyweight and something I would then have to undo again.)

**Comment by ArtOfCode-** [comment]
Sort answers by age.

[and now seriously: sort answers by age doesn't even exist yet. This and that are on the list :) ]

**Comment by cellio** [comment]
Well yeah, I know it's not there yet, but (a) I didn't know if you already had it but hadn't pushed yet and (b) either way, I didn't want the answer to my FR to be "hey, you can do this instead". :-)

**Comment by ArtOfCode-** [comment]
Fixed with 2de51fa9eda347c312b0d540034ec78e3e491005 for all notification types.
