### ISSUE TITLE
Please improve installation guidance

### ISSUE THREAD

**Issue by luap42** [ArtOfCode-/qpixel#55]
I have some troubles installing QPixel on my machine (dev environment). I think some fixes to the README.md installation instructions might be helpful. Here is, what gave me problems:

1. I am not from a RoR background. I didn't know, that I had to run `bundle install`. Please consider addding a line about it.
2. There was no `email.sample.yml` in the repo. I copied one from a prior fork I made and that fixed it.
3. The gem `tzinfo-data` was not in the Gemfile, but is required by the db setup script. 
4. When running the db setup script (`rails db:setup`), I get the following error message:

       Mysql2::Error: Table 'qpixel.site_settings' doesn't exist: SELECT `site_settings`.* FROM `site_settings`

    I am confused by this, because I thought the script would create that table.

5. Not a problem, but the setup script seems to have a missing post_type_id for the ToS ("Field 'post_type_id' doesn't have a default value")

(I am submitting this issue, so that I make you aware of the problems so far, although I was not yet able to finish it. Please help with 4. so that I can continue testing the instructions)

**Comment by luap42** [comment]
That has been everything so far. Although a note that you need to edit the DB to gain admin rights for the first user might also be helpful

**Comment by ArtOfCode-** [comment]
Aaand... that should be everything fixed. Thanks!
