### ISSUE TITLE
Deleted-post annotation is wrong for self-deletions

### ISSUE THREAD

**Issue by cellio** [ArtOfCode-/qpixel#60]
[This answer on Writing](https://writing.codidact.com/a/37987/39528) was deleted by its author.  The post notice says:

> This post was deleted because it violates the rules of this site. It can only be seen by users with the delete privilege.j

That first sentence would be true for a moderator or community deletion, but it casts aspersions on a post that the author merely thought better of.  Can we either vary the message based on who deleted it or generalize it?  For self-deletions I would change the first sentence to "This post was deleted by its author.".  If we can't vary the message, I would just say "This post has been deleted." and either the reason is obvious or people can ask on meta or vote to undelete.

**Comment by luap42** [comment]
Oh, right. That was introduced by me, when I worked on the redesign. I'll open a PR.

**Comment by luap42** [comment]
Fixed, please close. /cc @cellio @ArtOfCode-
