### ISSUE TITLE
Please restore user names to the question list

### ISSUE THREAD

**Issue by cellio** [ArtOfCode-/qpixel#61]
The site is now showing gravatars in place of user names.  I don't care if we show gravatars alongside that info (though they'd need to be smaller), but I really don't want to lose the names.  Names are meaningful to me; hard-to-see blobs of graphics are not.

I realize the name is available in a tooltip, but that's extra work and I don't know how to access it on a touch interface.  Maybe reverse it -- show the name as text and let the gravatar (and maybe other stats) appear in the tooltip.

I realize you changed other things, making the answer count and last-activity time huge to line up with the gravatars.  You'd have to revert that to make names fit.  I'd rather have the meaningful text even at that cost.

**Comment by ArtOfCode-** [comment]
Went with avatars because it was easiest to work with the Co-Design component that the list uses, but I might be able to fit usernames in somewhere. Their original placement didn't work at all with the component, so it had to change somehow and this was the easiest way. I'll take a look.

**Comment by ArtOfCode-** [comment]
(Just noticed this is on ArtOfCode- - could you copy this over to codidact/qpixel?)

**Comment by cellio** [comment]
Done: https://github.com/codidact/qpixel/issues/23

Sorry 'bout that.  This repo came up first and I didn't notice it was the wrong qpixel.
